{% set version = "4.0.0" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: robotframework-pabot
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/robotframework-pabot/robotframework_pabot-{{ version }}.tar.gz
  sha256: 9f418cea66a037da05e7f57a1c1109e2be2440f66953cbc21606e931abea9a81

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - pabot = pabot.pabot:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - natsort >=8.2.0
    - python >={{ python_min }}
    - robotframework >=3.2
    - robotframework-stacktrace >=0.4.1

test:
  imports:
    - pabot
    - pabot.py3
  commands:
    - pip check
    - pabot --version
    - pabot --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pabot.org
  summary: Parallel test runner for Robot Framework
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |-
    A parallel executor for Robot Framework tests. With Pabot you can split one
    execution into multiple and save test execution time.
  dev_url: https://github.com/mkorpela/pabot

extra:
  recipe-maintainers:
    - bollwyvl
