# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "5.2.2"
  python_check_max: "3.14"

package:
  name: robotframework-pabot
  version: ${{ version }}

source:
  - target_directory: dist
    url: https://pypi.org/packages/source/r/robotframework-pabot/robotframework_pabot-${{ version }}.tar.gz
    sha256: 497c3d72551c76eda21029df6a28c6b2ed227e63c4a8510e1c6a0690b9e2be91
  - target_directory: src
    url: https://github.com/mkorpela/pabot/archive/refs/tags/${{ version }}.tar.gz
    sha256: b40f9d49d5596cdd5fe8d8b62714e5f5726c4bda5de4f0f32736e49181c72a57

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - pabot = pabot.pabot:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=42
  run:
    - python >=${{ python_min }}
    - robotframework >=3.2
    - robotframework-stacktrace >=0.4.1

tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
      imports:
        - pabot
        - pabot.py3
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - python ${{ python_min }}.*
        - pytest-cov
    script:
      - cd src
      - coverage run --source=pabot --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=52

about:
  summary: Parallel test runner for Robot Framework
  license: Apache-2.0
  license_file: src/LICENSE
  description: |-
    A parallel executor for Robot Framework tests. With Pabot you can split one
    execution into multiple and save test execution time.
  homepage: https://pypi.org/project/robotframework-pabot
  repository: https://github.com/mkorpela/pabot
  documentation: https://pabot.org

extra:
  recipe-maintainers:
    - bollwyvl
