# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.3.0"

package:
  name: robotframework-pabot
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/r/robotframework-pabot/robotframework_pabot-${{ version }}.tar.gz
    sha256: 0da3d70055cad34c921b6c2ade80e839ea468307f326145f22d04d4fa7b996ab

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - pabot = pabot.pabot:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - natsort >=8.2.0
    - python >=${{ python_min }}
    - robotframework >=3.2
    - robotframework-stacktrace >=0.4.1

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports:
        - pabot
        - pabot.py3
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pabot --version
      - pabot --help

about:
  summary: Parallel test runner for Robot Framework
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |-
    A parallel executor for Robot Framework tests. With Pabot you can split one
    execution into multiple and save test execution time.
  homepage: https://pabot.org
  repository: https://github.com/mkorpela/pabot

extra:
  recipe-maintainers:
    - bollwyvl
